### ISSUE TITLE
sensor not loading

### ISSUE THREAD

**Issue by cosmos1978** [aex351/home-assistant-neerslag-card#45]
I get this error in ym logs

2024-05-15 17:52:09.981 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up command_line platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
await asyncio.shield(awaitable)
File "/usr/src/homeassistant/homeassistant/components/command_line/sensor.py", line 49, in async_setup_platform
command: str = sensor_config[CONF_COMMAND]
~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by aex351** [comment]
This seems to be related to the custom sensor that you have set. I think the requirements got changed slightly and there is an update pending. Other users proposed a change already. Will look into it.

Instead of using the `neerslag-card` that requires the setup of custom sensors, you could also use the `neerslag-app`, which is an all-in-one package. It contains both the `neerslag-card` and the sensors.
